# Generated by Django 3.1.6 on 2021-04-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('Surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('Age', models.IntegerField(verbose_name='Возраст')),
                ('Phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('Password', models.IntegerField(verbose_name='Пароль')),
                ('Email', models.CharField(max_length=100, verbose_name='Почта')),
            ],
        ),
    ]
