# Generated by Django 3.1.6 on 2021-04-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0012_auto_20210414_0950'),
        ('Client', '0002_auto_20210408_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('Address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('NumSeats', models.PositiveSmallIntegerField(verbose_name='Количество мест')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Дата')),
                ('Time', models.TimeField(verbose_name='Время')),
                ('NumPark', models.PositiveSmallIntegerField(verbose_name='Номер парковки')),
                ('Cost', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('FullnameClient', models.CharField(max_length=303, verbose_name='ФИО клиента')),
                ('PhoneNumberClient', models.CharField(max_length=100, verbose_name='Номер телефона клиента')),
                ('EmailClient', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('Cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.cinema', verbose_name='Кинотеатр')),
                ('Film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.allfilm', verbose_name='Фильм')),
            ],
        ),
    ]
