# Generated by Django 3.1.6 on 2021-03-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='Icon',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
