# Generated by Django 3.1.6 on 2021-03-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_allfilm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.AddField(
            model_name='allfilm',
            name='Href',
            field=models.TextField(null=True, verbose_name='Ссылка'),
        ),
    ]
