# Generated by Django 3.1.6 on 2021-03-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_auto_20210330_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allfilm',
            old_name='Href',
            new_name='Video',
        ),
    ]
