# Generated by Django 3.1.6 on 2021-03-30 13:27

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0007_auto_20210330_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfilm',
            name='Video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
