# Generated by Django 3.1.6 on 2021-04-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0008_auto_20210330_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfilm',
            name='Video',
            field=models.TextField(null=True, verbose_name='Ссылка'),
        ),
    ]
