# Generated by Django 3.1.6 on 2021-04-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0009_auto_20210407_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfilm',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
