# Generated by Django 3.1.6 on 2021-04-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0010_allfilm_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfilm',
            name='Mark',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Оценка'),
        ),
    ]
