# Generated by Django 3.1.6 on 2021-04-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0011_allfilm_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfilm',
            name='Mark',
            field=models.FloatField(null=True, verbose_name='Оценка'),
        ),
    ]
