# Generated by Django 3.1.6 on 2021-04-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0012_auto_20210414_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfilm',
            name='Schedule',
            field=models.TextField(max_length=1000, null=True, verbose_name='Расписание'),
        ),
    ]
